### Build the image from ubuntu 18.04 LTS
FROM ubuntu:18.04

### Allow to set-up HTTP(S) proxy using '--build-arg'
ARG http_proxy
ENV http_proxy ${http_proxy}
ARG https_proxy
ENV https_proxy ${https_proxy}
RUN echo 'http_proxy='$http_proxy'\nhttps_proxy='$https_proxy

### Clear local repository & install common tools
RUN apt-get clean \
 && apt-get update && apt-get install -y \
        curl            \
        git             \
        sudo            \
        unzip           \
        vim             \
        wget

### Configuration settings & options
ENV WORKSPACE           /opt
ENV MOUNT               $WORKSPACE/mnt

### Builder for Android Open Source Project (AOSP)
RUN : === install the main build tools \
 && apt-get update && apt-get install -y \
        openjdk-8-jdk git ccache automake lzop bison gperf build-essential zip curl zlib1g-dev g++-multilib python-networkx libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng maven libssl-dev bc bsdmainutils \
 && : === install additional packages \
          the 'gettext' package is not default installed by Ubuntu Server \
          the 'python-mako' package is required for building Android as a Guest \
          Android-IA requires 'libelf-dev','sbsigntool','dosfstools', and 'mtools' packages \
 && apt-get update && apt-get install -y \
        gettext python-mako \
        libelf-dev sbsigntool dosfstools mtools \
 && : === install the repo tool \
 && mkdir -p /usr/local/bin && curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > /usr/local/bin/repo && chmod a+x /usr/local/bin/repo

### Unset variables
ENV http_proxy ""
ENV https_proxy ""

### Mount points for holding external volumes
VOLUME $MOUNT
WORKDIR $MOUNT

ENV USER ubuntu
ENV PASSWD ubuntu
ENTRYPOINT \
    : === drop the default root privileges \
 && if [ $(id -u $USER > /dev/null 2>&1; echo $?) = 1 ]; then \
        useradd --uid `find $MOUNT -maxdepth 0 -printf '%U'` --create-home $USER; \
        echo "$USER:$PASSWD" | chpasswd; \
        adduser $USER sudo; \
    fi \
 && export USE_CCACHE=1 \
 && su $USER
